### ISSUE TITLE
How to track and graph the time of having food?

### ISSUE THREAD

**Issue by lamyergeier** [SamAmco/track-and-graph#104]
I want to track and graph the time at  which I consume breakfast, lunch, dinner and snacks. It is not the time duration and I don't want to add any numerical value. I just want to see weekly graph at which time I have theme meals, and every day what is the time gap between these meals. Also a daily graph which shows the time stamp as a point for all these meals (indicating how often I had these meals and when I had these meals).

How can I do this?

**Comment by stheid** [comment]
I think you can easily do it using the multiple choice tracker. Just add the meals as choices. Than you can use the graph to plot "time between"

Or you make numerical values and set the default to "1". The timestamps are recorded automatically. if you are only interested in the timestamps and not in the values it should be easy to work around that.

**Comment by SamAmco** [comment]
Yeah I think as @stheid said this is more of a plotting issue. You can use Track and graph to record the data using multiple choice but you might have to export to excel and build your own graphs for something like this right now.

**Comment by SamAmco** [comment]
@hberntsen drew my attention to something here. If you want to draw a graph of what time of day you eat lunch each day, you can actually do this by using a time duration data type and putting the time since 00:00 as the value. So if the time is 13:00 you just track 13 hours. Then you can create a graph where the Y-axis is time of day and the X axis is the days. You could do the same for breakfast and dinner and draw them all on the same graph if you like.
