### ISSUE TITLE
Add seedvault backup integration

### ISSUE THREAD

**Issue by lurkingcode** [SamAmco/track-and-graph#119]
Hi, not sure how complicated this is, but it seems that the app does not allow to be part of the automated backup system that seedvault offers (which is the native way google does it, if I understand correctly), it would be nice to have such an option since it works great (I just tested the backup thingy to make sure it works and it went fine, using linegeos 18.1). I'm stilly making weekly backups for track & graph for this reason, since there is not automated way to do it. Thanks for the app and your time!

**Comment by maguilara** [comment]
According to some posts (https://www.reddit.com/r/LineageOS/comments/kuzf9f/force_seedvault_to_backup_apps_which_refuse_to_be/) it's because the APK has somes flags that disable the backup and seedvaults respects that, not sure if that's the case in this app.

**Comment by SamAmco** [comment]
Interesting, thanks for letting me know. Yes you are right i have disabled allowBackup. The simple reason for this is that in order to support this backup/restore feature you need to implement a BackupAgent that knows how to backup and restore the data. This shouldn't be too hard, but I never got around to it before. I will consider this for a future release but i can't say how long it will take me to get it done.

**Comment by gadgetguy08** [comment]
I have the same request.  I found this info from SeedVault:

So if  your favorite app is not included in backups, you can contact the app's developers and make them aware of this option. For example, this (https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71) is how the Transportr app enabled only encrypted backups.

**Comment by SamAmco** [comment]
Hi all. This should be fixed in the next release (currently rc-v2.1.0 available for beta testers on play store only atm). I just set auto backup to true in the end, no need to exclude anything really. Sorry for the wait.
