### ISSUE TITLE
Feature Request: Add auto backup

### ISSUE THREAD

**Issue by Mirodin** [SamAmco/track-and-graph#12]
First of I love this app, was looking for something like this for ages!

I like that there is a way to export my data manually but I would like to propose a functionality to trigger a backup of all the data Track&Graph has every day/month etc. I use another app which is called Car Report that provides this feature. Every day I start the app for the first time a backup is created to a location which one can choose freely.

Since smartphones today tend to day/get lost/stolen/... sometimes it would be a shame to lose a lot of entries just because one forgot to export the data. Plus I track quite a lot of different things within the app which makes exporting every group a little bit tedious.

**Comment by SamAmco** [comment]
Hi, I agree this sounds like a good idea. I may not have time to implement this for quite a while though I'm afraid as I'm very busy at the moment.

**Comment by SamAmco** [comment]
Update: I have now implemented a backup and restore page in the app so you can manually back up the whole database to where ever you like. There is not currently an automatic trigger option and this is not a priority for me at the moment, but at least now it's a lot easier to do a full backup manually. App reviews seem to be moving very slowly on Google Play at the moment but I'm hoping it will be up in beta within the next couple of weeks and then released some time after that assuming everything is fine.

**Comment by tristanbrown** [comment]
This is the most important feature I'm still hoping to see in this app. I'm using Track&Graph to log personal data on my phone, that I'd like to be able to parse, process, and display in my own webapp. I love that I can backup the whole database to a file in a directory that syncs with my desktop, where I can have scripts running to parse the SQLite db. The only bottleneck in this process is having to manually hit the backup button. Automate the backup (and possibly the restore, for full-sync capabilities), and this app becomes amazingly powerful.

**Comment by PellelNitram** [comment]
I also love the Track and Graph app! Thanks to all contributors and the maintainer for creating this app!

Also, I'd love to see a way to automatise the backup up of my data.

What do you think of the following approach: If the data **location could be adjusted**, then other apps could take care of doing the actual backup.

**For example**, I use FolderSync to backup the images I have captured on my phone every night. That only works, of course, because the Camera app stores the captured data, i.e. the images, in a location on the phone that is easily accessible by the backup app I use.

If it was possible to just point the location of the data to a custom location in Track+Graph, then a similar workflow would work here with, probably, minimal programming work.

What do you say? Is a **adjustable data location** a realistic avenue for a first order backup automatisation feature? :-)

**Comment by SamAmco** [comment]
That is an interesting idea @PellelNitram . I do suspect though that this might actually be more difficult than a service that periodically copies the internal room database file to a given location. Reason being Room doesn't (as far as I know) support opening directly from a file, it first copies the file to the internal storage directory and then opens it for modification there.

**Comment by PellelNitram** [comment]
Thanks @SamAmco for your feedback! Unfortunately I have never used the Room database, hence I cannot comment on the question if Room can read data in a user-accessible location easily or if a dedicated periodic copy program is easier to implement.

Maybe someone else knows?

**Comment by jdckr** [comment]
I would also love that feature. How about using  broadcast for this? So you could use any Automation app to trigger the export. AndOtp has a feature like this https://github.com/andOTP/andOTP

**Comment by SamAmco** [comment]
In v3.7.x there is now an auto-backup feature that will use the Storage Access Framework (SAF) to allow you to periodically backup your database to a cloud provider e.g. Drive, Dropbox etc. It's still in beta but it will come to release in the next week or so. Hope this helps people.
