### ISSUE TITLE
displaying a group in two columns (change GUI)

### ISSUE THREAD

**Issue by tevig** [SamAmco/track-and-graph#183]
1. If user click on '+' button - we have 3 type data:
- track
- graph
- group
the track is displayed in two columns
Graph and group in one columns
it would be great if any data type could be displayed in two columns

2. Change click logic
Now if I click in the track - I open log, if I click small button '+' - I add data.
Perhaps it would be more convenient to make a small 'log' button, and when you click on any area of the track, add a data

**Comment by SamAmco** [comment]
First of all. If there are two issues, please create two tickets. One ticket should be specific to one issue and should contain enough detail to explain the issue clearly. Secondly I still don't really understand what you are asking for here: 

1. Currently the trackers take up one column each. Why would you want them to take up more? I don't see any benefit, also I don't see why you would want graphs to be smaller. The current behaviour is that they fill the screen .. so if you have a tablet big enough to fit 5 trackers across, graphs will have a width of 5 columns. Groups always take 2 columns. 
2. Why do you want to swap these UI elements around? I personally like it the way it is. Is this just a design preference? 

Again it may help if you use images or diagrams to explain what the problem is and how you want it to be solved.
