### ISSUE TITLE
Suggestion: Option to show only integers in chart

### ISSUE THREAD

**Issue by Kozonak** [SamAmco/track-and-graph#19]
Tracking group with date and time only, which only has 1s in it, is displayed in the graph as decimals. Not sure if bug or feature request, but an option to only show whole numbers would be useful. 

Graph is set as fixed range 10, no averaging, plotting daily totals with scale 1.

![image](https://user-images.githubusercontent.com/3283978/74961027-0d74e600-5416-11ea-81c2-fd47a92ac24c.png)

**Comment by SamAmco** [comment]
Hi. Yes sorry, the issue here is that the Y-axis is always divided into 10 sub-sections (including 0). If your max was set to 9 you'd have all integers on the Y-axis. I'm not entirely sure the best way to solve this, perhaps there is a clever general way to determine the best number of sub-sections to use for the Y-axis? I don't have one off the top of my head.

I was thinking of solving this problem in a slightly different way in the near future however. I would like to add the ability to have point labels and clear dots on the graph where the data points should be. I think this would make graphs such as yours much more readable where you don't have thousands of data points on one graph.

**Comment by Kozonak** [comment]
Using 9/18/27 kinda solves the problem, the graphs look better now.

> make graphs more readable

Dailyo has some readable graphs.

![image](https://user-images.githubusercontent.com/3283978/75545942-37d72c80-5a30-11ea-9b2b-d5cf0e892f7a.png)

But it only has 5 items on the Y axis. Maybe Track could have compact view by default (showing 0 - 5 - 10 for ex) and a detailed view option to show the entire scale.

The dates could also be at 90 degrees instead of 45, and it could fit every day there instead of every three like now.

**Comment by SamAmco** [comment]
@Kozonak yes I think part of the key with that dailyo graph is the use of dots/nodes .. I'm going to add an option to have them and have them annotated with numbers soon.

**Comment by Kozonak** [comment]
Since there is a custom Y height wouldnt it be better to divide by that instead of 10, so you have all the steps shown regardless of how tall the graph is?

It might get crowded above something like 50, maybe have it as an optional box.

**Comment by SamAmco** [comment]
Not sure this is a complete enough solution. I regularly track things with decimal places e.g. between 0 and 1

**Comment by SamAmco** [comment]
@Kozonak If it's ok with you I would like to close this issue since you can now annotate points on the graph with nodes and values if you are looking for greater accuracy.
