### ISSUE TITLE
Newer versions make editing existing trackers impossible 

### ISSUE THREAD

**Issue by aproposnix** [SamAmco/track-and-graph#201]
Hi, I just tried to change one of my trackers and it takes me to a screen to make a new tracker instead of letting me change the existing tracker. Is this by design? I'm currently using version 3.0.1

Impact: I can no longer modify any existing tracker before v3. 

EDIT: Can you also confirm whether it's possible to downgrade since the v3 release? Or, has the data format somehow changed?

**Comment by Kanten** [comment]
Hi, 
that's exactly what I'm dealing with. 
pre 3.0 Version Multiple Choise Tracker can't be edit and some of the options i created are gone.
Even after a full Reset of the App, there is no chance to establish a new Mutliple Choise Tracker.

**Comment by ScalableCodex** [comment]
> Hi, 
> 
> that's exactly what I'm dealing with. 
> 
> pre 3.0 Version Multiple Choise Tracker can't be edit and some of the options i created are gone.
> 
> Even after a full Reset of the App, there is no chance to establish a new Mutliple Choise Tracker.

So downgrading doesn't work? Or? Because I'm thinking of going back a version.

**Comment by Kanten** [comment]
Importing the data.csv into V3.x works

**Comment by SamAmco** [comment]
As @Kanten suggested you can use CSV to move your data to an old version but you'll lose your graphs etc. I didn't expect people to get so upset with the new version tbh .. I honestly think it's better its just different which is confusing people. If you can't see the name/description and other settings when you edit a tracker that's definitely a bug though.

**Comment by ScalableCodex** [comment]
> @aproposnix Hi. Downgrading would probably be a bit tricky tbh as the data has changed. I think maybe what you're experiencing is that the concept of multiple choice is gone now so if you go to edit your tracker you will not see the labels/values pre-set up in the tracker. Instead these are inferred by looking at your past tracked values. If you wanted to change a label/value you can do this from the tracker history screen. (Take a look at the FAQ on that) .. the new version is more flexible as labels and values are not fixed anymore. 
> 
> 
> 
> Can you please confirm whether this is the issue. Presumably if you go to edit a tracker you still see the name and description etc? 

Honestly the app has just become so much more confusing to use. Like when I go to add data to let's say, the 5th of this month. It sets it to the 4th. So if I do wanna add old data, I have to select the 6th so it gets added as the 5th. Very weird. And yeah editing data is just not really possible now.

**Comment by aproposnix** [comment]
I'm not sure about anyone else but I've lost my data. None of the backups are working. This was disappointing.

**Comment by SamAmco** [comment]
Ok this is turning into a bit of a general discussion. I would prefer if we can keep issues specific otherwise they become unmanageable. 

The way I see it there are two issues here unless anyone can give me concrete evidence otherwise:

1. When you select the date it chooses the day before. This is a known issue and there is another issue open for it. I will try to fix it asap but I'm away until Tuesday now. 
2. You're confused about your preset multiple choice answers not being there anymore. Please take a look at the FAQ. There is actually an issue to add this feature back in as well but I'm not convinced it's necessary or a good idea right now. 

I'm going to close this issue because both of these are covered elsewhere.

@aproposnix It's a sqlite database. You can open it with any sqlite browser application. The easiest way for you to downgrade will be to use CSV export/import though. The database structure has fundamentally changed between those two versions.
