### ISSUE TITLE
App crash while rename a group 

### ISSUE THREAD

**Issue by Ilav1** [SamAmco/track-and-graph#265]
I don't know why but the group names are switched. Maybe after the last update.

Now the group 1 should be named like the group 2 and group 2 should be named like group 1.

When I try to rename the groups, the app is crashing without any information. The app just close itself. Ant the second try, I get an Android message because the app crashed a few times.

Maybe someone else has the same issues?

**Comment by SamAmco** [comment]
It looks like renaming groups is crashing the app :/ whoops. Thanks for letting me know. I will try and fix soon. 

I'm not sure what you mean about groups having the wrong names though. Is the contents of those groups correct? Perhaps the groups are just showing in the wrong order rather than showing with the wrong name.

**Comment by Ilav1** [comment]
Forget the names of the group. It was my fault, nothing changed, sorry!

Not just rename a group end in an crash also changing the colour... If you need more details let me know:)

**Comment by SamAmco** [comment]
Ok this should be fixed in v3.8.3. Thanks again for raising this issue.
