### ISSUE TITLE
Feature request: Widgets

### ISSUE THREAD

**Issue by riotbib** [SamAmco/track-and-graph#4]
Hi @SamAmco, thanks a lot for the app! Always wished for something like this.
One feature I'd be happy to have:

Android widgets for the various tracks. So a user – for example for numerical input – only has to tab the correct widget and it counts. Would simplify the process and encourage tracking.

**Comment by SamAmco** [comment]
Hi riotbib, thanks for the feedback. I agree widgets would be super useful and I intend to add them at some point. I don't have a lot of time on my hands at the moment though so there's no guaranteeing when this will happen I'm afraid.

**Comment by pizzapim** [comment]
I'm attempting to add this functionality at https://github.com/pizzapim/track-and-graph. It's my first time coding Kotlin so don't expect a flawless implementation soon :)

**Comment by SamAmco** [comment]
That's awesom, thanks @pizzapim  .. Could you break down the design for me (in terms of UX/UI). It would be great to align on that before you do too much work.

**Comment by pizzapim** [comment]
This is the structure I have in mind:

- Simple configuration activity to choose what you want to track.
- The widget should display the same information as the cards, including a button to track. We might be able to reuse the layout somewhat.
- Clicking the button creates a dialog to enter tracking details. I'm reusing the existing fragment for this.

Shall I create a pull request with a checklist of features/requirements?

**Comment by SamAmco** [comment]
Yes If you could create a PR it would be great. It sounds like a good plan but the more design documentation/description you can add in the PR the better. 

Code wise I will obviously review it before merging and may ask for specific changes or just make them my self. 

Actually the project is quite young as I'm sure you can tell and it's not really set up well for contributors yet. There are no tests and some of the code needs considerable refactoring. You are the first person to get involved with the actual code other than my self so that's pretty exciting. I will try to make it a little more friendly to newcomers over time. 

Let me know if you need any help understanding anything, I will do my best.

**Comment by pizzapim** [comment]
@SamAmco I suppose this issue can be closed now.

**Comment by SamAmco** [comment]
I will close it when the feature is actually released. Won't be long, I'm bundling in a couple of other improvements with the next release that I'm working on now.

**Comment by SamAmco** [comment]
Thanks again @pizzapim for implementing this
