### ISSUE TITLE
Feature request: Dark splash screen

### ISSUE THREAD

**Issue by laborhase** [SamAmco/track-and-graph#52]
Hi there, I am super happy ever since the dark theme came to the app because I use the app a lot in dark environments. I'd like to suggest that the splash screen could be dark as well to avoid that "flash" upon starting the app.

**Comment by SamAmco** [comment]
Yes you are right it probably should be dark. Hopefully I will look at this soon. Thanks

**Comment by SamAmco** [comment]
I'm going to close this issue after further investigation. I looked into the issue and it turns out that if your device is in dark mode when you start the app then the splash screen is dark. The splash is only light if you override the system default theme in the app from light to dark. This happens because the app must first load up and read what the overridden theme value is before it can change the theme, so at the time the light splash screen is shown there is no way for the app to know that you actually want to see the dark splash screen. I hope this makes sense. Overall I think this is a small issue and could be solved by most users by simply switching to dark mode via the OS rather than overriding the OS theme in the app.

**Comment by laborhase** [comment]
That's understandable and now that you say it: The apps with dark flash screen have it regardless of which theme I chose within them.
Thanks for looking into it!
