### ISSUE TITLE
feature request: averaging improvement

### ISSUE THREAD

**Issue by pictoys** [SamAmco/track-and-graph#55]
hi there,
thanks for this great app!
i miss one thing though, i wish i could graph every entry as a line, so on days when there is no entry it goes back to zero. it seems like the daily average is a bit off as this would be the solution. would be great to have this functionality in graph and histogram.
max of day would also be very useful!

thanks again, best tracking app out there!

**Comment by SamAmco** [comment]
Hi I think what you're looking for is Daily total + Daily moving average? For more details check out the "How are moving averages and plot totals calculated?" section in the FAQ section of the app.

**Comment by pictoys** [comment]
thanks, i think daily total did it actually. it was just a bit off as one of the entries was on 23.30h for some reason it oved it to the next day.

**Comment by SamAmco** [comment]
Moving averages take into account everything in the time period prior to a given data point. So if it's a daily moving average and one day at 23:30 you track 1.0 and the next day at 23:00 you track 0, then this will show on the second day as 0.5 because there are two data points within your 24 hour window. If you don't want this behaviour maybe you just want to plot daily total? I'm not entirely sure what you're trying to achieve.
