### ISSUE TITLE
Number of choices for multiple choices is limited to 10

### ISSUE THREAD

**Issue by ydnax** [SamAmco/track-and-graph#65]
started using track and graph and discovered the limit for choices for multiple choice measurements.
Is there a technical reason for the limit?

I try to track the things i do and there are more than 10 different thins so a higher limit(or no limit at all) would be appreciated

**Comment by ydnax** [comment]
ok so i had some time to look at the source code. i assume the setting is here https://github.com/SamAmco/track-and-graph/blob/cf043990f4b70744c42298daf63b87000c49396d/app/src/main/java/com/samco/trackandgraph/database/TrackAndGraphDatabase.kt#L37 

are there practifcal reasons why it is this low and what would be needed to increase it?

**Comment by SamAmco** [comment]
This is mainly for UI reasons. For example the options are listed below a pie chart. If there are too many it could start to look bad/broken. It probably could be unbounded if these UI issues were fixed. The graph cards need to have adaptive heights that can accommodate for unlimited options though. Also the full screen graph view will need to deal with the situation in which there are too many options to fit on the screen by adding scrolling behaviour.

**Comment by ydnax** [comment]
ok i see. i haven't used the stats screens much yet so they didn't come to mind. maybe i'll find some time in the future to look at these issues. for now i'll just use a patched apk for myself so i have noone uyt byself to blame for the broken stats screens.

**Comment by SamAmco** [comment]
Yeah no worries. Sorry about that

**Comment by Mrnofish** [comment]
> This is mainly for UI reasons. For example the options are listed below a pie chart.
> The graph cards need to have adaptive heights that can accommodate for unlimited options though. Also the full screen graph view will need to deal with the situation in which there are too many options to fit on the screen by adding scrolling behaviour.

As far as I'm concerned, there is no need for unbounded. 

But anyway, when the user tries to add more than 10, why not display a prompt warning the user that graphs can break on smaller displays?

As a sidenote, I think for a non-programmer it would make more sense for the first multiple choice to be tagged as 1 rather than 0.

**Comment by SamAmco** [comment]
> when the user tries to add more than 10, why not display a prompt warning that the graphs can break on smaller displays?

Yeah this could be a good mid-term solution but there is probably a better way which is to have more dynamic UI. The graph card sizes are fixed right now for example. 

> As a sidenote, I think for a non-programmer it would make more sense for the first multiple choice to be tagged as 1 rather than 0.

Probably a separate ticket but I think having a 0 is helpful in some cases. For example if you have the options "none", "some", "lots" and then you scale that data by 10 to put it on a graph. You want "none" to still be 0.

**Comment by Mrnofish** [comment]
> Yeah this could be a good mid-term solution but there is probably a better way which is to have more dynamic UI. The graph card sizes are fixed right now for example.

Agreed, however for the building a data series right now without having to fuse options together, it would be still useful and appreciated.

**Comment by SamAmco** [comment]
Update on this. I believe I've fixed the issues with dynamic UI for graph cards, however I still haven't removed the limit on the number of multiple choice answers because if you create a pie chart then the colors are assigned automatically. So if you have more than 12 options you would end up with duplicate colors. I did change the maximum from 10 to 12 though so you can at least have as many options as there are colors. If I can fix the issues with pie charts somehow then I suppose I can remove this limit all together. I will try and take another look at this at some point.

**Comment by Mrnofish** [comment]
Great, thanks for the update and letting us know.

**Comment by android-sam** [comment]
This should be fixed in v3.0.0 (currently in open beta)
