### ISSUE TITLE
Bug?: Moving average window is one day longer / unclear wording

### ISSUE THREAD

**Issue by hhpmmd** [SamAmco/track-and-graph#70]
This affects all moving average windows, but obviously is more prominent in the smaller ones. _(Actually I haven't tested the daily moving average case yet.)_

When I select the weekly moving average, I would expect an average over the last week, so an average over 7 days including the current one. The app however currently averages one more day, 8 in total.

The same is true for the three day moving average, which averages four days in total: today and the three days prior.

I hope the problem is clear and my understanding of the wording is correct.

A straightforward solution can probably be found by further inspecting the `calculateMovingAverages` function, which I could do after it's confirmed that this is indeed a bug and not the apps desired behaviour.

**Comment by SamAmco** [comment]
I suspect what you are seeing here was intentional although perhaps not intuitive?

If i track something with a value of 3 at 2:00 in the afternoon and then the next day I track something with a value of 1 at 1:30 in the afternoon and I'm using an averaging period of 1 day then the value shown for 1:30 on the second day will be 2 (the average of 3 and 1). This is because when the algorithm calculates what value to place for 1:30 on day 2 it calculates it as the average of the value at 1:30 and any other value within the 24 hour period prior to it (which contains the value tracked at 2:00 the previous day). Although the average contains points from 2 separate days it is still an average of all points within a 24 hour period (or 1 day). If you wanted to exclude the point from the day before you could use daily totals in conjunction with daily average because the daily total algorithm makes a data point at the end of each day containing the sum of all data points in that day. 

Does that make sense?

**Comment by hhpmmd** [comment]
I think I get your point. When using plot-when-tracked i think the behavior you describe is fine.

I noticed the 'issue' however when I used the plot-daily-totals accumulation together with the averaging (e.g. plot daily totals, three day average) and if I understand your last sentence correctly that is not what's expected.

**Comment by SamAmco** [comment]
Yes you are right this shouldn't happen in this case. It is probably because all values are placed at the same time of day e.g. 23:59:59:999 .. and no doubt it is including a value it shouldn't right at the cut off.
