### ISSUE TITLE
Line Graph preview isn't the same as the result

### ISSUE THREAD

**Issue by hhpmmd** [SamAmco/track-and-graph#79]
Hey, I just updated my app and noticed that the previews didn't look like I would expect them. They don't have the custom bounds_min / bounds_max set.
This probably has to do with the `listMode` situation where the custom bounds get disabled when the graph is **not** in listMode so that when the graph is in fullscreen-mode it is possible to scroll around (with the behavior in preview-mode as a side effect).

Not sure what the best solution would be. Either change listMode to fullscreenMode so it's easier to handle that specific case on it's own or use an enum for the viewMode (with options LIST, FULLSCREEN, PREVIEW).
Let me know your thoughts on this and I can probably fix it on my own.

**Comment by SamAmco** [comment]
Good spot. Actually I had to hotfix another bug in that PR after releasing it because there was a null pointer exception if the user tried to create a graph from an empty data set. So it would be good to double check this scenario when you modify the code. Also I'm not sure how you get the app on your phone but if you go through google play then you might want to consider joining the beta if you haven't already just in case you spot other bugs. 

With regard to this specific issue, I think preview mode should behave exactly like listMode? .. I'm actually not entirely sure why it doesn't already. I can try and take a look this weekend though. I'm trying to find time for some graph view stuff atm anyway so might be best if I just take a look my self on the weekend.

**Comment by SamAmco** [comment]
Actually I just took a look and I think I found the fix. I will put it in the next release but I might wait until I've finished the feature I'm working on before releasing. Thanks for letting me know.
