### ISSUE TITLE
Suggestion - Simple dated incremental counter type

### ISSUE THREAD

**Issue by khaytsus** [SamAmco/track-and-graph#94]
I use an app called Keep Track but it is weird in that some of its counters I can put notes on, some can't, ui is confusing, etc. But it does one thing I want and that is just track when I last did a thing, like mowed the grass or changed a filter. I like to look back to see how many times I did something last year or when I started doing it, frequency of the task, that sort of thing.

Could an additional type be added that could basically just fill in date/time, let me optionally put in a note, and basically just auto increment a value? Or maybe I'm missing a way to do this which already exists? Thank you!

**Comment by SamAmco** [comment]
All data points carry a timestamp, a value and can optionally carry a note. If you just want to know the time you did something then i recommend you just use a numerical input type and just have every data point with a value of 1. This way you can do stuff like add them up, see how many there are in a given time window etc. You should be able to easily create a graph of this data that will show you how many times you mowed the lawn each month for example. You could also see how long since you last mowed the lawn using the time since last stat.
